# This file was generated by GoReleaser. DO NOT EDIT.
class Findgs < Formula
  desc "findgs can search your starred repositories in the Github which matched searching text from title, description, topic, and README."
  homepage ""
  version "1.0.6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gjbae1212/findgs/releases/download/v1.0.6/findgs_1.0.6_Darwin_x86_64.tar.gz"
    sha256 "da9c70630a04b9d83c660f0e660f40b7635be6f5b8c9a2fc2a9214fde4cbd074"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/gjbae1212/findgs/releases/download/v1.0.6/findgs_1.0.6_Linux_x86_64.tar.gz"
      sha256 "307e59bcffb942b892ce493a8002806f85f74c7e9c2ccb2b0fa383fd645a67f5"
    end
  end

  def install
    bin.install "findgs"
  end
end
